### ISSUE TITLE
Excercise Bug: 07-Very-Specific-Rules

### ISSUE THREAD

**Issue by dzagar88** [learnpack/learnpack#1291]
Describe the bug:

**1. Exercise Name:** 07-Very-Specific-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

Changed Odd background color to yellow and it says it isn't yellow but it is

**Comment by UmiKami** [comment]
Make sure your style property looks like this:

```css
tr:nth-child(odd) {
	background: yellow;
}
```
