### ISSUE TITLE
Excercise Bug: 05-Specificity

### ISSUE THREAD

**Issue by amalia1501** [learnpack/learnpack#1300]
Describe the bug:

**1. Exercise Name:** 05-Specificity

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

**Comment by UmiKami** [comment]
```css
ul li {
	background: blue;
}

#thirditem {
	background: yellow;
}
/****** DON NOT EDIT ANYTHING ABOVE THIS LINE ****/

#thirditem{
       background: true;
}

```
The code above is more than enough to override the style of item and hence there is **NO** need to use ` !important`  to change the background color to green. Since the instructions and tests tell you to use it, I changed the base code to:

```css
ul li {
	background: blue;
}

li + #thirditem {
	background: yellow;
}
/****** DON NOT EDIT ANYTHING ABOVE THIS LINE ****/
```

With the code above, doing:

```css
#thirditem {
     background: green;
}
```

Would **not be enough** to override the color of the background, that means, we would be forcing the student to be more specific by using `!important` which is what we want.
