### ISSUE TITLE
Excercise Bug: 06-Practicing-Rules

### ISSUE THREAD

**Issue by lugras** [learnpack/learnpack#1395]
Describe the bug:

**1. Exercise Name:** 06-Practicing-Rules

**2. Repository URL:** https://github.com/4GeeksAcademy/css-tutorial-exercises-course

Point 7 said apply padding to all sides of the paragraph but the padding on the solution is just to left side.

**Comment by UmiKami** [comment]
The solution is applying the following style to that aforementioned paragraph:

```css
#id1 {
	background: rgba(255, 255, 255, 0.2);
	padding: 5px;
}
```

The following property applies a style of 5px to all sides of an element: 
`padding: 5px;`
